### ISSUE TITLE
raw_to_datastack ZipStore error

### ISSUE THREAD

**Issue by ktilburg** [fligt/maxrf4u#1]
When running this piece of code on the latest version 0.1.17 and a fresh install of the dependencies:
```
for raw_file, rpl_file in zip(raw_files, rpl_files):
    mx.raw_to_datastack(raw_file, rpl_file, output_dir='maxrf4u/data/datastacks/')
    print(f'{raw_file} done')
```

I encountered the following error:

> 101 zs = zarr.ZipStore(datastack_file, mode='w') 
    103 if verbose: 
    104     print(f'Writing: {datastack_file}...')

AttributeError: module 'zarr' has no attribute 'ZipStore'

When reading the zarr documentation it seemed that zarr.ZipStore became zarr.storage.ZipStore

**Comment by fligt** [comment]
Hi Koen, 

I suspect that we are confronted with major updates in two package dependencies: zarr and dask. I don't see your error now because my current installation works with zarr 2.18.3. I will update to zarr 3.0.4 to try to reproduce your error. 

On my machine with dask version 2024.11.2 I get another error when trying to create the datastack files: 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 4
      2 n = len(raw_files)
      3 print(f'{i}[/](http://localhost:33765/){n-1} Creating datastack from: {raw_file}                                                                                                          ...', end='\r')
----> 4 mx.raw_to_datastack(raw_file, rpl_file, output_dir='[./data/interim/maxrf/datastacks/](http://localhost:33765/lab/tree/notebooks/data/interim/maxrf/datastacks/)')

File [~/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/maxrf4u/storage.py:108](http://localhost:33765/lab/tree/notebooks/~/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/maxrf4u/storage.py#line=107), in raw_to_datastack(raw_file, rpl_file, output_dir, datapath, verbose, flip_horizontal, flip_vertical)
    106 # compute and write maxrf data to zipstore 
    107 with ProgressBar(): 
--> 108     smoothed.to_zarr(zs, component=datapath) 
    110 zs.close()
    112 # compute sum and max spectra and append to zipstore 

File [~/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/dask/array/core.py:3015](http://localhost:33765/lab/tree/notebooks/~/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/dask/array/core.py#line=3014), in Array.to_zarr(self, *args, **kwargs)
   3004 def to_zarr(self, *args, **kwargs):
   3005     """Save array to the zarr storage format
   3006 
   3007     See https://zarr.readthedocs.io for details about the format.
   (...)
   3013     dask.array.to_zarr : equivalent function
   3014     """
-> 3015     return to_zarr(self, *args, **kwargs)

File ~/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/dask/array/core.py:3875, in to_zarr(arr, url, component, storage_options, overwrite, region, compute, return_stored, **kwargs)
   3872     raise ValueError("Cannot use `region` keyword when url is not a `zarr.Array`.")
   3874 if not _check_regular_chunks(arr.chunks):
-> 3875     raise ValueError(
   3876         "Attempt to save array to zarr with irregular "
   3877         "chunking, please call `arr.rechunk(...)` first."
   3878     )
   3880 storage_options = storage_options or {}
   3882 if storage_options:

ValueError: Attempt to save array to zarr with irregular chunking, please call `arr.rechunk(...)` first.
``` 

This issue is perhaps related to: 

[https://github.com/dask/dask/issues/11544](https://github.com/dask/dask/issues/11544)

To be continued...
